# Generated by Django 5.0.7 on 2024-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='duration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='poster',
            field=models.ImageField(upload_to='images'),
        ),
    ]
